tap "lognseth/tap"
brew "chezmoi"
brew "fzf"
brew "gh"
brew "gitleaks"
brew "tfenv"
brew "zoxide"
brew "lognseth/tap/azenv", trusted: true
cask "chatgpt"
cask "ghostty"
cask "tailscale-app"
cask "transmission"
cask "vlc"
cask "zed"
brew "dockutil"
