apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2025-07-22T07:11:11Z"
  name: sniff
spec:
  caveats: |
    This plugin needs the following programs:
    * wireshark (optional, used for live capture)
  description: |
    When working with micro-services, many times it's very helpful to get a capture of the network
    activity between your micro-service and it's dependencies.

    ksniff use kubectl to upload a statically compiled tcpdump binary to your pod and redirecting it's
    output to your local Wireshark for smooth network debugging experience.
  homepage: https://github.com/eldadru/ksniff
  platforms:
  - bin: kubectl-sniff
    files:
    - from: kubectl-sniff-darwin
      to: kubectl-sniff
    - from: static-tcpdump
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: c59b5c9ea84d6cb771096f1246c919b71389f9d4234e858f4929208957e561fd
    uri: https://github.com/eldadru/ksniff/releases/download/v1.6.2/ksniff.zip
  - bin: kubectl-sniff
    files:
    - from: kubectl-sniff-darwin-arm64
      to: kubectl-sniff
    - from: static-tcpdump
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: c59b5c9ea84d6cb771096f1246c919b71389f9d4234e858f4929208957e561fd
    uri: https://github.com/eldadru/ksniff/releases/download/v1.6.2/ksniff.zip
  - bin: kubectl-sniff
    files:
    - from: kubectl-sniff
      to: .
    - from: static-tcpdump
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: c59b5c9ea84d6cb771096f1246c919b71389f9d4234e858f4929208957e561fd
    uri: https://github.com/eldadru/ksniff/releases/download/v1.6.2/ksniff.zip
  - bin: kubectl-sniff.exe
    files:
    - from: kubectl-sniff-windows
      to: kubectl-sniff.exe
    - from: static-tcpdump
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: c59b5c9ea84d6cb771096f1246c919b71389f9d4234e858f4929208957e561fd
    uri: https://github.com/eldadru/ksniff/releases/download/v1.6.2/ksniff.zip
  shortDescription: Start a remote packet capture on pods using tcpdump and wireshark
  version: v1.6.2
status:
  source:
    name: default
